import React from "react";
import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { TripWithRelations } from "@/features/trip/api/tripActions";

Font.register({
  family: "Noto Sans JP",
  fonts: [
    { src: "https://fonts.gstatic.com/s/notosansjp/v52/-KyWJ7mE_N4S0-pIs4W6B8kH.ttf", fontWeight: 400 },
    { src: "https://fonts.gstatic.com/s/notosansjp/v52/-KyWJ7mE_N4S0-pIs4W6B8kH.ttf", fontWeight: 700 },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Noto Sans JP",
    backgroundColor: "#FFFFFF",
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#000000",
  },
  subtitle: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 10,
  },
  section: {
    marginTop: 20,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    backgroundColor: "#F3F4F6",
    padding: 6,
    marginBottom: 10,
  },
  eventRow: {
    flexDirection: "row",
    marginBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F3F4F6",
    paddingBottom: 4,
  },
  eventTime: {
    width: 60,
    fontSize: 10,
    fontWeight: "bold",
    color: "#4B5563",
  },
  eventContent: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 11,
    fontWeight: "bold",
  },
  eventDesc: {
    fontSize: 9,
    color: "#6B7280",
    marginTop: 2,
  },
  tipRow: {
    marginBottom: 6,
    padding: 6,
    backgroundColor: "#FFFBEB",
    borderRadius: 4,
  },
  tipTitle: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#92400E",
  },
  tipBody: {
    fontSize: 9,
    color: "#B45309",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999999",
    borderTopWidth: 0.5,
    borderTopColor: "#EEEEEE",
    paddingTop: 10,
  },
});

export default function TripReportDocument({ trip }: { trip: TripWithRelations }) {
  return (
    <Document title={`${trip.title} Report`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{trip.title}</Text>
          <Text style={styles.subtitle}>
            {trip.location} | {new Date(trip.startDate).toLocaleDateString("ja-JP")} - {new Date(trip.endDate).toLocaleDateString("ja-JP")}
          </Text>
        </View>

        {trip.days.map((day) => (
          <View key={day.id} style={styles.section}>
            <Text style={styles.sectionTitle}>Day {day.dayNumber}: {day.title || "Itinerary"}</Text>
            {day.events.map((event) => (
              <View key={event.id} style={styles.eventRow}>
                <Text style={styles.eventTime}>{event.time}</Text>
                <View style={styles.eventContent}>
                  <Text style={styles.eventTitle}>{event.title || event.foodName}</Text>
                  {(event.desc || event.foodDesc) && (
                    <Text style={styles.eventDesc}>{event.desc || event.foodDesc}</Text>
                  )}
                </View>
              </View>
            ))}
          </View>
        ))}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Travel Tips & Knowledge</Text>
          {trip.tips.map((tip) => (
            <View key={tip.id} style={styles.tipRow}>
              <Text style={styles.tipTitle}>{tip.title}</Text>
              <Text style={styles.tipBody}>{tip.body}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>Generated by Memoir Travel Planner</Text>
      </Page>
    </Document>
  );
}
